#This is a hack to help include libs in daisy projects.
#see daisylib core make file to see why.
#it can be fixed by modifying that file
C_INCLUDES ?= -include stm32h7xx.h

#include every new folder in the library here.
C_INCLUDES += -I../../lib/
C_INCLUDES += -I../../lib/timers