# Project Name
TARGET = Quantizer

# Sources
CPP_SOURCES = Quantizer.cpp

Sia_Lib= ../../lib/
include $(Sia_Lib)/Makefile

# Library Locations
LIBDAISY_DIR = ../../../libDaisy/
DAISYSP_DIR = ../../../DaisySP/

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
