# Project Name
TARGET = Drum808

# Sources
CPP_SOURCES = Drum808.cpp bass_drum.cpp snare_drum.cpp high_hat.cpp fm_drum.cpp

# Library Locations
LIBDAISY_DIR = ../../../libDaisy/
DAISYSP_DIR = ../../../DaisySP/

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
